on:
    push:

env:
  CARGO_TERM_COLOR: always


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.rustup
          key: toolchain-${{ runner.os }}-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo tools
        run: cargo install --locked mdbook

      - name: Build book
        run: mdbook build

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./book