name: Deploy mdBook site to Pages

on:
    push:
        branches: [ "main" ]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo install --locked mdbook@0.4.30
            - run: cargo install --locked mdbook-linkcheck@0.7.7
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Build with mdBook
              run: mdbook build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./book/html

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
