name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install --locked mdbook@0.4.30
      - run: cargo install --locked mdbook-linkcheck@0.7.7
      - name: Build mdbook
        run: |
          mdbook build
          mdbook test
      - name: Index.html exists
        run: test -f book/html/index.html